### ISSUE TITLE
Slider memory leak

### ISSUE THREAD

**Issue by Belozerow** [navasmdc/MaterialDesignLibrary#111] opened 2015-01-20 13:46 UTC
Slider has memory leaks, I guess, in onDraw, because when it is visible, logcat starts spam:
"GC_FOR_ALLOC freed 1921K, 22% free 19472K/24736K, paused 14ms, total 16ms"

**Comment by emileb** [comment] 2015-01-22 17:02
I reported this last month (it was closed). The problem is invalidate() is called in onDraw in many of the controls. This mean Megabytes of data is constantly garage collected and is a massive drain on battery whenever the view is visible.

**Comment by itsalltoomuch** [comment] 2015-01-28 08:40
I have the same issue. So many OutOfMemory crash reports

**Comment by filipc** [comment] 2015-02-02 10:32
fixed in pull request #138

**Closed** 2016-11-07 21:22 UTC
